from openai import OpenAI
import subprocess

client = OpenAI(base_url="http://localhost:1234/v1", api_key="random")


def write_file(path: str, content: str):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def ask_bot(question: str) -> str:
    prompt = f"""
    You are a programming assistant. Write a correct Python solution code for this problem:
    {question}
    - Only return valid Python code (no explanation).
"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-20b", messages=[{"role": "user", "content": prompt}]
    )
    print(response)
    return response.choices[0].message.content


def run_code(file_name="final.py"):
    try:
        result = subprocess.run(
            ["python3", file_name], capture_output=True, text=True, timeout=10
        )
        print("=== Program Output ===")
        print(result.stdout)
        if result.stderr:
            print("=== Errors ===")
            print(result.stderr)
    except subprocess.TimeoutExpired:
        print("Error: Program took too long to run")


if __name__ == "__main__":
    question = input("Enter the problem needs to generate the solution code: ")
    code = ask_bot(question)
    print("\n=== Code generated by bot ===\n")
    print(code)
    write_file("final.py", code)
    run_code("final.py")
